In [236]:
import numpy as np
np.random.seed(42)

num_states = 2
state_size = 15

# states
Vs = np.random.randint(0, 2, (num_states, state_size), dtype=int)
Vs = 2 * Vs - 1

print("Vs\n", Vs)

W = np.zeros((state_size, state_size), dtype=int)
print("W\n", W)

Vs
 [[-1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1  1]
 [-1  1  1  1 -1  1 -1  1  1  1  1  1  1  1  1]]
W
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [237]:
for i in np.arange(state_size):
    for j in np.arange(state_size):
        # Identity is zero, no self-influence
        #
        if i == j:
            continue
            
        # Only calculate upper triangular matrix and copy
        # already calculated values in the lower triangle
        #
        if i > j:
            W[i,j] = W[j,i]
            continue
        
        W[i,j] = 0
        
        for s in np.arange(num_states):
            W[i,j] += Vs[s,i]*Vs[s,j]

print("W trained\n", W)

W trained
 [[ 0 -2  0  0  2 -2  2  0  0 -2  0  0  0  0 -2]
 [-2  0  0  0 -2  2 -2  0  0  2  0  0  0  0  2]
 [ 0  0  0  2  0  0  0  2  2  0  2  2  2  2  0]
 [ 0  0  2  0  0  0  0  2  2  0  2  2  2  2  0]
 [ 2 -2  0  0  0 -2  2  0  0 -2  0  0  0  0 -2]
 [-2  2  0  0 -2  0 -2  0  0  2  0  0  0  0  2]
 [ 2 -2  0  0  2 -2  0  0  0 -2  0  0  0  0 -2]
 [ 0  0  2  2  0  0  0  0  2  0  2  2  2  2  0]
 [ 0  0  2  2  0  0  0  2  0  0  2  2  2  2  0]
 [-2  2  0  0 -2  2 -2  0  0  0  0  0  0  0  2]
 [ 0  0  2  2  0  0  0  2  2  0  0  2  2  2  0]
 [ 0  0  2  2  0  0  0  2  2  0  2  0  2  2  0]
 [ 0  0  2  2  0  0  0  2  2  0  2  2  0  2  0]
 [ 0  0  2  2  0  0  0  2  2  0  2  2  2  0  0]
 [-2  2  0  0 -2  2 -2  0  0  2  0  0  0  0  0]]


In [240]:
v = 2 * np.random.randint(0, 2, (state_size)) - 1
th = np.zeros(state_size)

print("v\n", v)

num_iterations = 5

for _ in range(num_iterations):
    v_old = np.copy(v)
    v_in = np.zeros((state_size), dtype=int)

    energy_sum_a = 0
    energy_sum_b = 0
    
    for i in np.arange(state_size):
        for j in np.arange(state_size):
            v_in[i] += W[j,i] * v[j]
            
            energy_sum_a += W[i,j] * v[i] * v[j]
            
        energy_sum_b += th[i] * v[i]
            
        if v_in[i] >= th[i]:
            v[i] = 1
        else:
            v[i] = -1

            
    print(f"{v_old} -> {v} {'*' if (v_old == v).all() else ''}")
    e = -(1/2) * energy_sum_a + energy_sum_b
    print(f"Hopfield Energy:\t{e}")

v
 [-1 -1 -1 -1 -1  1  1 -1  1  1  1  1 -1  1 -1]
[-1 -1 -1 -1 -1  1  1 -1  1  1  1  1 -1  1 -1] -> [ 1  1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] 
Hopfield Energy:	-6.0
[ 1  1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] -> [ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] 
Hopfield Energy:	-84.0
[ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] -> [ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] *
Hopfield Energy:	-98.0
[ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] -> [ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] *
Hopfield Energy:	-98.0
[ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] -> [ 1 -1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1] *
Hopfield Energy:	-98.0
